export function generateDockerfile(imports: string[]): string {
    // Determine base image based on imports
    const hasScAnaly = imports.some(imp => 
        ['scanpy', 'anndata', 'scvi'].some(lib => imp.includes(lib))
    );
    
    const baseImage = hasScAnaly 
        ? 'continuumio/miniconda3:latest'
        : 'python:3.11-slim';
    
    return `# Dockerfile generated by BioWorkflow Generator
FROM ${baseImage}

# Set working directory
WORKDIR /workflow

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    build-essential \\
    git \\
    && rm -rf /var/lib/apt/lists/*

# Copy environment file
COPY envs/environment.yaml .

# Create conda environment
RUN conda env create -f environment.yaml && \\
    conda clean -afy

# Activate environment
SHELL ["conda", "run", "-n", "bioworkflow", "/bin/bash", "-c"]

# Copy workflow files
COPY . .

# Set entrypoint
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "bioworkflow", "snakemake"]
CMD ["--cores", "all"]
`;
}

export function generateDockerignore(): string {
    return `node_modules/
.git/
.vscode/
*.pyc
__pycache__/
.snakemake/
.DS_Store
*.log
`;
}
